spring.application.name=SB_Thymeleaf_01

#Database Connection
spring.datasource.url = jdbc:postgresql://localhost:5432/CloraTshirt
spring.datasource.username = postgres
spring.datasource.password = yash03


#JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

stripe.secret.key =sk_test_51SUjs3FWCjv2i6cEGCEsV5v3Wlcbf9CayIb0nlUxhOmxQl0cz0con6Q3L6Eax38D19uHD5dQCD4J1fYbxO4LCzWS00EQOqhSVi
stripe.public.key =pk_test_51SUjs3FWCjv2i6cESz4HrbXETu5RIuiP4yVycQ0JnbWptm7v7FpCH0qCuKEx49jwuZ5DGDr3pMNhPMNehDRer5N0003XOotCqv

server.max-http-request-header-size=64KB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB